repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        stages: [commit]
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml", "--fix"]
        stages: [commit]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        stages: [ commit ]
        args: [ "--config=pyproject.toml" ]
      - id: nbqa-ruff
        args: [ "--config=pyproject.toml", "--fix" ]
        stages: [ commit ]
