name: Generate Conversion Script

on:
  push:
    branches:
      - main
      - tsmith/4790-auto-pro
#    paths:
#      - '**/cellxgene_schema_cli/cellxgene_schema/ontology_files/*.csv.gz'
#      - '**/cellxgene_schema_cli/cellxgene_schema/ontology_files/*_diff.txt'
#      - '**/cellxgene_schema_cli/cellxgene_schema/ontology_files/all_ontology.json.gz'


permissions:
  contents: write
  pull-requests: write

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r migration_assistant/requirements.txt
      - name: Run Conversion Script Generator
        run: |
          make generate-conversion-script
      - name: Get Version
        id: get_version
        run: |
          echo "version=$(make show-current-version)" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'AUTO: update convert.py to schema_version ${{ env.version }}'
          title: 'AUTO: update convert.py to schema_version ${{ env.version }}'
          body: 'This is an automated PR to update convert.py to schema_version ${{ env.version }}.'
          branch: auto/update-convert-py-to-${{ env.version }}
          reviewers: bento007
          assignees: bento007

