name: Gene Bump Dry Run

on:
  push:
    branches:
      - main
    paths:
      - '**/cellxgene_schema_cli/cellxgene_schema/ontology_files/*.csv.gz'
      - '**/cellxgene_schema_cli/cellxgene_schema/ontology_files/*_diff.txt'
      - '**/cellxgene_schema_cli/cellxgene_schema/ontology_files/all_ontology.json.gz'


permissions:
  id-token: write
  contents: read

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r migratoin_assistant/requirements.txt
      - name: Run Conversion Script Generator
        run: |
          make generate-conversion-script
      - name: lint changes
        uses: pre-commit/action@v3.0.0
      - name: Make new PR
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # TODO create branch
          git add ./cellxgene_schema_cli/cellxgene_schema/convert.py
          git commit -m "AUTO: update ontologies"
          git push
          # TODO open new PR against branch
