name: Updated Ontologies

on:
  pull_request:
    paths:
      - '**/cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml'

jobs:
  ontology-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: ontology-processing
        run: |
          pip install -r cellxgene_schema_cli/requirements.txt
          make download-ontologies -C cellxgene_schema_cli
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./cellxgene_schema_cli/cellxgene_schema/ontology_files/all_ontology.json.gz
          git commit -m "AUTO: update ontologies"
          git push
