name: Push tests

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  ontology-changes:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    permissions:
      pull-requests: read
    outputs:
      owl_info: ${{ steps.filter.outputs.owl_info }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            owl_info:
              - 'cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml'

  ontology-processing:
    runs-on: ubuntu-latest
    needs: ontology-changes
    if: github.ref != 'refs/heads/main' && needs.ontology-changes.outputs.owl_info == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install requirements
        run: |
          pip install -r cellxgene_schema_cli/requirements.txt
      - name: owl-processing
        if: ${{ needs.ontology-changes.outputs.owl_info == 'true' }}
        run: |
          make download-ontologies -C cellxgene_schema_cli
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./cellxgene_schema_cli/cellxgene_schema/ontology_files/all_ontology.json.gz
          git commit -m "AUTO: update ontologies"
          git push

  lint:
    runs-on: ubuntu-latest
    needs: ontology-processing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v3
      - name: check backend
        uses: pre-commit/action@v3.0.0

  unit-tests:
    runs-on: ubuntu-latest
    needs: ontology-processing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r cellxgene_schema_cli/requirements.txt
          pip install pytest
      - name: Unit tests
        run: make unit-test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
